envs:
  production:
    description: "production environment"
    devices: !!inc/file devices-production.yml
    app: firmware/app1
  develop:
    description: "lab environment"
    devices: !!inc/file devices-lab.yml
    app: firmware/app-lab
