envs:
  production:
    description: "My env description"
    devices: !!inc/file devices-production.yml
    app: firmware/app1
  develop:
    description: "My dev env"
    devices: !!inc/file devices-lab.yml
    app: firmware/app-lab
