testing:
#   pre_flight: "echo ....."
   script: testing/validate-led.py
#    env_vars: 
#       - $ENV1
   device_update:
     ota_method: 'spanner shipper'
     env: 'production'
     repo: 'current'
